#!/bin/bash

ROOT="/vagrant/picoCTF-web"

# Shutdown the server
echo "Shutting down nginx"
sudo service nginx stop

# Clean out the old files
echo "Cleaning up old files"
sudo rm -rf /srv/http/ctf/*
sudo chown -R vagrant: /srv/http/ctf

echo "Generating web"
cd $ROOT/new_web
tmux kill-session -t ctfweb 2> /dev/null
if [[ $1 = "production" ]]; then
    gulp production deploy
else
    gulp copy cjsx deploy
    tmux new-session -s ctfweb -d "cd $ROOT/new_web && gulp watch"
fi

# Make sure everything is in UNIX format.
sudo dos2unix -q /srv/http/ctf/*.html

# Copy config over
sudo cp $ROOT/config/ctf.nginx /etc/nginx/sites-enabled/ctf

# Make sure everything is readable
sudo chmod -R +r /srv/http/ctf/*

# Start the server
echo "Restarting the server"
sudo service nginx start

echo "Installing the API"
sudo pip3 install --upgrade $ROOT

# Clear the cache
echo "Clearing the API cache"
api_manager database clear cache

START_CMD="python3 run.py"
if [[ $1 = "production" ]]; then
    START_CMD="./gunicorn_start.sh"
fi

if [[ $1 = "stresstest" ]]; then
    START_CMD="python3 run.py -d -k test_key"
fi

#Start Ctf API
echo "Starting the Ctf API"
tmux kill-session -t ctfapi 2> /dev/null
tmux new-session -s ctfapi -d "cd $ROOT && $START_CMD"

#Start Stats caching daemon
echo "Starting the statistics caching daemon"
tmux kill-session -t ctfstats 2> /dev/null
tmux new-session -s ctfstats -d "daemon_manager -d $ROOT/daemons cache_stats share_instances"
